# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Stage 1: Build the TypeScript code
FROM node:22-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy the package.json and pnpm-lock.yaml for installing dependencies
COPY package.json pnpm-lock.yaml ./

# Install the dependencies with pnpm (assuming it's preferred due to pnpm-lock.yaml)
RUN npm install -g pnpm && pnpm install

# Copy the rest of the application files
COPY . .

# Build the TypeScript code
RUN pnpm exec tsc

# Stage 2: Create the runtime image
FROM node:22-alpine AS runtime

# Set the working directory
WORKDIR /app

# Copy compiled JavaScript from the builder stage
COPY --from=builder /app/dist /app

# Set environment variable for the Node.js runtime
ENV NODE_ENV=production

# Command to run the application
CMD ["node", "index.js"]
